--CRIAR BANCO DE DADOS

CREATE DATABASE wptcar;


-- CRIAR TABELAS
CREATE TABLE veiculos ( 
id_veiculos INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
marca VARCHAR(64) NOT NULL,
modelo VARCHAR(64) NOT NULL,
email VARCHAR(64) NOT NULL,
telefone VARCHAR(64) NOT NULL,
valor VARCHAR (64) NOT NULL,
autor VARCHAR(64) NOT NULL)